version: '2.1'
services:
  front:
    container_name: front
    build: front
    restart: always
    ports:
      - 80:4000
    networks:
      - project_network

  banner-service:
    container_name: banners
    build: banner-service
    restart: always
    ports:
      - 9090:9090
    networks:
      - project_network

  account-service:
    container_name: accounts
    environment:
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    build: account-service
    restart: always
    ports:
      - 6000:6000
    networks:
      - project_network

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    build: mongodb
    restart: always
    networks:
      - project_network
  
  statistics-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: sqshq/piggymetrics-mongodb
    build: mongodb
    restart: always    
    networks:
      - project_network

  statistics-service:
    container_name: statistics
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
    restart: always
    build: statistics-service
    ports:
      - 9080:9080
    networks:
      - project_network
    

networks:
  project_network:
    driver: bridge
    # external: true
    # internal: true

# networks:
#   project_network:
#     name : project_network
    # external: true
