security:
  oauth2:
    client:
      clientId: banner-service
      clientSecret: ${BANNER_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /banners
  port: 9090

feign:
  hystrix:
    enabled: true